### ISSUE TITLE
New window is not maximized

### ISSUE THREAD

**Issue by R2D221** [iainbeeston/tab-less#4]
When a new tab is created, it's moved to a new window. If the current window is maximized, I expect the new one to be maximized too, but rather it appears small (and I seem to have no control over the size of this new window).

On the other hand, actually creating it maximized seems to be buggy, according to this report:
https://code.google.com/p/chromium/issues/detail?id=459841

**Comment by iainbeeston** [comment]
Can you please tell me what operating system you use? On Mac OS, new tabs created from a maximised window are also maximised. Is this a windows-only bug? (If so which version of windows?)

**Comment by R2D221** [comment]
I'm on Windows 8.1. I haven't tested Mac or Linux, so it might be Windows-only.

**Comment by iainbeeston** [comment]
I'll see if I can reproduce. Thanks for letting me know.

**Comment by iainbeeston** [comment]
I think I've fixed it. I've released version 0.3.6 of the extension to the app store, with the fix. Could you please update your extensions, make sure that the version listed is 0.3.6, then tell me if you still have this issue?

**Comment by R2D221** [comment]
OK, it works now. Thanks :smile:
